### PR TITLE
Menu dropdown shows table options when table is active

### LINKED ISSUE #634: Add table properties menu
Part of #348

### LINKED ISSUE #652: Migrate the TableView file to JS
- Rewrite the `TableView.ts` file to `TableView.js` file.
- Classnames like `tableWrapper` needs to be converted with proper `neeto-editor-` prefix.
- Once merged raise a new PR from the `table-extension` branch to the `main` branch.

@gaagul _a

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #634 
Fixes #652 

**Description**

- Added: table properties in menu
- Changed: TableView to js

**Checklist**

- [x] I have made corresponding changes to the documentation.
- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**
@AbhayVAshokan _a

### CODE REVIEW

**Comment by AbhayVAshokan** [comment]
@subins2000 the review app is taking forever to get released. Can you please check if something is missed out?

**Comment by subins2000** [comment]
@sreeram-venkitesh Can you take a look at why the release is failing. This is unusual.

**Comment by sreeram-venkitesh** [comment]
[Here](https://gist.github.com/sreeram-venkitesh/87495ee194062e5c4ddbc482130a5d63) are the logs from the web dyno, which is going into CrashLoopBackOff.

Its throwing a `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` error. 

CC: @AbhayVAshokan

**Comment by sreeram-venkitesh** [comment]
The release job has been completed, but the cronjob has not sent the callback to the dashboard app marking the release as complete, since the web dyno is crashing because of the above issue.

**Comment by AbhayVAshokan** [comment]
@sreeram-venkitesh what about the newer changes? The release seems to be completed. But the deployment is a `Bad Gateway`.

**Comment by sreeram-venkitesh** [comment]
I can see the dyno running but it was going into `OOMKilled` state occasionally. This is when a kubernetes pod get terminated because it runs out of memory. As a temporary fix, I have manually increased the memory limit of the dyno to 1GB. It is running now, but I will continue to monitor it for some time.

**Comment by AbhayVAshokan** [comment]
I'll check why is it taking too much memory.

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a https://vimeo.com/802002206/781f4aa393

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please verify the changes, these changes will fix #652 also.

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a

**Review by AbhayVAshokan — APPROVED** [review]
Nice work 👌

**Pull request merged**
