### PR TITLE
React 18 migration

### LINKED ISSUE #890: React 18 migration
Ref: https://github.com/bigbinary/neeto-engineering-web/issues/484

### PR DESCRIPTION
**Pull request by neenu-chacko**
- Fixes #890 

**Description**

**Checklist**

- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by neenu-chacko** [comment]
@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
@neenu-chacko I managed to upgrade the storybook to the latest version and the warning still persists. 

Here is a reference from the storybook team: https://github.com/storybookjs/storybook/issues/17831#issuecomment-1205173409. It seems like this is still not fixed on their end. This is only present on the documentation side. So it should work fine. Please assign the PR to Gaagul for a thorough verification if everything else is done.

**Comment by neenu-chacko** [comment]
@gaagul _a Please thoroughly test and verify everything works as expected.

**Comment by gaagul** [comment]
> @gaagul _a Please thoroughly test and verify everything works as expected.

LGTM

**Pull request merged**
