### PR TITLE
Improves the list item backspace behaviour.

### LINKED ISSUE #1216: Improvement to the list item backspace behaviour
https://neeto-engineering.neetoplanner.com/admin/projects/product-management/list/441

https://abhay-ashokan.neetorecord.com/watch/7238f14e-e991-474e-a654-96c94fbbed17

@deepakjosp _a

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #1216

**Description**
changes-to-backspace-bullets-editor

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@AbhayVAshokan  _a please review.

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@deepakjosp _a: https://abhay-ashokan.neetorecord.com/watch/84c5ab6c-9c86-4f8d-82d5-e8be914b684a

**Comment by deepakjosp** [comment]
@AbhayVAshokan  I've fixed the mentioned issue. I've identified an issue with the sub items. I'll assign the PR back for review once I fix that.

**Comment by deepakjosp** [comment]
@AbhayVAshokan  _a fixed the identified edge case. Please review.

**Review by AbhayVAshokan — APPROVED** [review]
Awesome 👌

**Pull request merged**
