### PR TITLE
Added a popover component above `Link` mark when selected

### LINKED ISSUE #871: Allow redirecting to clickable ink's url from the Editor itself
https://www.loom.com/share/ad9702dc05fd4668be7de9fc0ddbf0c0

@AbhayVAshokan _a Please look into this and assign to someone if we can take it up.

### LINKED ISSUE #874: Feature request for being able to open links quickly
https://www.loom.com/share/60a2b0ff38374210855cce10750dffc4

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #874 
- Fixes #871 

**Description**

- Added: popover component above `Link` mark when selected

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a
- [ ] Update the UI as shown below. Also, add a proper placeholder when the link is empty.
image
- [ ] Changes in behavior: https://vimeo.com/863163213/61fc434a25

**Comment by gaagul** [comment]
> - [ ] Update the UI as shown below. Also, add a proper placeholder when the link is empty.

I prefer the current Ui because it will be suitable for smaller editor as well, the longer Ui might not look good in many places especially when editor is inside pane.

Please let me know your thoughts on this.

**Comment by AbhayVAshokan** [comment]
Can you please post a screenshot with a smaller editor? The other column approach is wasting too much space. This looks really clean.

**Comment by gaagul** [comment]
> Can you please post a screenshot with a smaller editor? The other column approach is wasting too much space. This looks really clean.

In similar uscases to neetoSite as shown below, in my opinion the longer one will not look good

Screenshot 2023-09-19 at 10 26 33 PM

**Review by AbhayVAshokan — APPROVED** [review]
@gaagul _a https://vimeo.com/867800237/57196d8c4e

Please merge after this change.

**Pull request merged**
