### PR TITLE
Removed inconsistencies in styling of editor content

### LINKED ISSUE #658: Reading experience vs Writing experience
https://www.loom.com/share/49ea01941a24434a8be599ab7dea3f9c

@AbhayVAshokan _a

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #658 

**Description**

- Removed: inconsistencies in styling of editor content

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
~~- [ ] I have verified the functionality in some of the neeto web-apps.~~
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have fixed the Integrated attachments styling.

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a Removed conflicts.

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a a few more changes: https://vimeo.com/806710165/e41bd1b1b9

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have updated the styles, Please let me know if the padding given to the lists needs improvement.

**Review by AbhayVAshokan — APPROVED** [review]
Nice work 👌 
Here is one final change: https://vimeo.com/806738886/66a1b35a8b

Please merge once done.

**Pull request merged**
