### PR TITLE
Dependencies to peerDependencies

### PR DESCRIPTION
**Pull request by farhanlatheef**
- Ref:  https://github.com/bigbinary/neeto-commons-frontend/pull/1135

Should only be merge after https://github.com/bigbinary/neeto-commons-backend/pull/2822

**Description**

**Checklist**

- [x] I have made corresponding changes to the documentation.
~- [ ] I have updated the types definition of modified exports.~
- [ ] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by AbhayVAshokan** [comment]
Fixes https://github.com/bigbinary/neeto-desk-web/issues/19265.
Refer to https://abhay-ashokan.neetorecord.com/watch/09b43b06-ddfc-4b2b-84fc-5683ecbe4c7f for the explanation.

**Comment by AbhayVAshokan** [comment]
Released v1.31.0-beta.1.

@farhanlatheef: Can you please raise a PR in neetoDesk with the newer changes and verify the functionality.

**Comment by farhanlatheef** [comment]
Issue 1:  Says content required, even though there is content. 
Screenshot 2024-04-17 at 4 16 40 PM

Issue 2: Don't know exactly what cause below console error, but I think it is coming from neetoeditor
Screenshot 2024-04-17 at 4 16 28 PM


neetoDesk PR: https://github.com/bigbinary/neeto-desk-web/pull/19279

@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
@farhanlatheef _a fixed the issue.

**Comment by AbhayVAshokan** [comment]
Closing this PR in favour of neetoEditor revamp.

**Pull request closed without merging**
