### PR TITLE
Added option to upload multiple images

### LINKED ISSUE #708: Ability to upload multiple images
Ref: https://github.com/bigbinary/neeto-kb-web/issues/3729

- The user should be able to upload multiple images. Both selection and drag and drop of multiple images should directly insert them into the editor content.
- We can remove the step to enter a caption altogether. A two-step process depending on the number of selected images does not show consistency.

@gaagul _a please take this up with priority _t.

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #708

**Description**

- Added: ability upload multiple images

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
-~~ [ ] I have updated the types definition of modified exports.~~
- [X] I have verified the functionality in some of the neeto web-apps.
- [X] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**
 
@AbhayVAshokan  _a

### CODE REVIEW

**Comment by gaagul** [comment]
@AbhayVAshokan _a

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a nice work. Please make these changes in UI: https://vimeo.com/811890414/67b816fd31

**Comment by gaagul** [comment]
> @gaagul _a nice work. Please make these changes in UI: https://vimeo.com/811890414/67b816fd31

@AbhayVAshokan The above mentioned changes to UI will require some more time, can I please  increase the estimated time so that this weeks works can be scheduled accordingly.

**Comment by AbhayVAshokan** [comment]
Yes

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have Improved the UI for upload progress of images, Please review.

**Review by AbhayVAshokan — APPROVED** [review]
@gaagul _a please make the changes that we discussed.

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have made the changes as discussed.

**Review by AbhayVAshokan — APPROVED** [review]
LGTM

**Pull request merged**
