### PR TITLE
Editor table revamp.

### LINKED ISSUE #1159: Editor table revamp
Part of https://github.com/bigbinary/neeto-editor/issues/1100

---

- Fix usability issues for the table extension.
- The table menu needs to be revamped. You may refer to https://www.richer-text.com/ for inspiration.

@deepakjosp  _a

### PR DESCRIPTION
**Pull request by deepakjosp**
- Fixes #1159

**Description**
New UI
image

Old UI
image

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
- [ ] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@AbhayVAshokan This feature requires new icons which will be worked on by Avinash in this [ticket](https://github.com/bigbinary/neeto-editor/issues/1181).

**Comment by deepakjosp** [comment]
@AbhayVAshokan  _a please review.

cc: @praveen-murali-ind

**Review by AbhayVAshokan — APPROVED** [review]
@deepakjosp _a: https://abhay-ashokan.neetorecord.com/watch/7788b493-6120-43d5-bf14-88ba20b58fd9

**Comment by deepakjosp** [comment]
@praveen-murali-ind  _a please review.

**Review by praveen-murali-ind — APPROVED** [review]
LGTM.

**Pull request merged**
