### PR TITLE
Added aria-label to editor content

### LINKED ISSUE #969: Add aria-* labels to make editor more accessible
While working on neeto-editor with Playwright, we noticed that a few commands such as [fill](https://playwright.dev/docs/next/api/class-locator#locator-fill) were not working. This was because the editor did not fall under the roles of `<input>` or `<textarea>` and is not a `[contenteditable]` tag. The same can be an issue with accessibility as screen readers might not identify the editor to be a text field. Adding the proper aria labels should help resolve this issue and improve the testing experience as well.

@AbhayVAshokan _a
enhancement _t

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #969 

**Description**

- Added: aria-label attribute to editor content

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
~~- [ ] I have verified the functionality in some of the neeto web-apps.~~
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@VarunSriram99 _a

### CODE REVIEW

**Comment by gaagul** [comment]
@VarunSriram99 I have added "aria-label" to editor, please review the changes and let me know if more attributes are needed.

**Comment by VarunSriram99** [comment]
@gaagul can you add the proper aria-role labels as well?

**Comment by VarunSriram99** [comment]
@gaagul additionally adding a `role`, `aria-disabled` and `aria-controls` (if applicable) is recommended so that the elements are more easily accessible.

**Comment by gaagul** [comment]
> @gaagul can you add the proper aria-role labels as well?

Is "aria-roledescription" = "editor" enough or do you have something specific in mind?

> @gaagul additionally adding a `role`, `aria-disabled`, `aria-role` and `aria-controls` (if applicable) is recommended so that the elements are more easily accessible.

By role did you mean the "aria-roledescription" ?

**Comment by VarunSriram99** [comment]
> > @gaagul can you add the proper aria-role labels as well?
> 
> Is "aria-roledescription" = "editor" enough or do you have something specific in mind?
> 
> > @gaagul additionally adding a `role`, `aria-disabled`, `aria-role` and `aria-controls` (if applicable) is recommended so that the elements are more easily accessible.
> 
> By role did you mean the "aria-roledescription" ?

@gaagul 
We can add the `role` attribute to specify the aria-role.
`role="textbox"` should be good enough. Adding roledescrption can be useful as well in case of screen readers.

We can also add in labels like
```
  role="textbox"
  aria-multiline="true"
  aria-labelledby="labelId"
  aria-required="true" (based on required prop)
  aria-disabled="false" (based on disabled prop)
  aria-controls="controls-id" (optional for the toolbar controls)
```

**Comment by gaagul** [comment]
> We can also add in labels like

Thanks for the clarification, I will add the necessary labels.

@gaagul _a

**Pull request merged**
