### PR TITLE
Updated styles to match changes in neetoUi

### LINKED ISSUE #637: Check for neetoUI's breaking changes in neetoEditor
neetoUI is bringing several breaking changes into the styles. The same pattern should be followed in neetoEditor. Also, check and solve UI issues due to these changes.

https://github.com/bigbinary/neeto-ui/pull/1583

spike _t
@AbhayVAshokan _a

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #637 

**Description**

- Changed: custom styles to match updated neetoUi color contrast

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Comment by gaagul** [comment]
@AbhayVAshokan I have tested the editor in neetoDesk and neetoKb and everything is working as expected.
The main changes were changing color `--neeto-ui-gray-700` to `--neeto-ui-gray-600` and `--neeto-ui-gray-800` to `--neeto-ui-gray-700` to maintain the expected contrast, other breaking changes to neetoUi does not affect editor.

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a Conflicts have been resolved.

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a https://vimeo.com/802935383/cb06f5bea9

**Comment by gaagul** [comment]
@AbhayVAshokan Can you please confirm if i have to change the backgrounds of slash commands and mentions.

1.  (--neeto-ui-gray-700)

Screenshot 2023-02-28 at 12 32 59 PM

2. (--neeto-ui-gray-600)
Screenshot 2023-02-28 at 12 33 18 PM

**Comment by AbhayVAshokan** [comment]
@gaagul let's keep the first one.

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have improved the color contrast and everything looks readable now, Please let me know if I have to make further changes.

**Review by AbhayVAshokan — APPROVED** [review]
@gaagul _a please merge after making this changes:

image

Every menu option in the Bubble menu should have the same background color as the wrapper.

**Pull request merged**
