### PR TITLE
Updates EditorContent to support adding anchor tags around headers for easy navigation.

### LINKED ISSUE #1252: Update EditorContent to support adding anchor tags around headers for easy navigation.
@deepakjosp _a

- [ ] Implement navigation to headers in EditorContent component.
- [ ] Create a script to implement navigation to headers to be used in the EUI screens that do not have ReactJS.

0.75D _t

_Originally posted by @AbhayVAshokan in https://github.com/bigbinary/neeto-engineering-ui-ux/issues/347#issuecomment-2426430430_

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #1252 

| **Description** |
|-|
| EditorContent |
| image |
| NeetoWebsite |
| image |
| Rails template |
| image |

**Checklist**

- [x] I have made corresponding changes to the documentation.
- [x] I have updated the types definition of modified exports.
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@AbhayVAshokan  _a please review.

I've used the `Script` component in NextJS to fetch the scripts when the page is loaded on the browser.

```js
      <Script
        src="https://cdn.jsdelivr.net/npm/@bigbinary/neeto-editor/dist/codeBlockHighlight.js"
        strategy="beforeInteractive"
      />
```

cc: @praveen-murali-ind

**Review by AbhayVAshokan — APPROVED** [review]
@deepakjosp _a: 

1. Mention about the above comment in the story (Output/Docs)
2. Update the props table in Output/Docs.
3. https://abhay-ashokan.neetorecord.com/watch/c94f8737-7185-4ff7-881c-aa773dc7a806

**Comment by deepakjosp** [comment]
@AbhayVAshokan implemented the suggestions. @praveen-murali-ind  _a please review.

**Review by praveen-murali-ind — APPROVED** [review]
LGTM.

**Pull request merged**
