### PR TITLE
Created a popover for adding links to editor content

### LINKED ISSUE #883: Issues with links
Ref: https://vimeo.com/862884264/d2a0a39604

bug _t
@gaagul _a

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #883 

**Description**

- Added: popover to add links to editor

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a

There are a few issues with this approach:
- [x]  Pressing enter should submit the form. Instead, it is replacing the text content.
- [x] Add more spacing between the two inputs and the buttons (use `space-y-2`).
- [x] Update the label of the `link` button to `Done`.
- [x] The placement of the popover is wrong. So it's more confusing.
- [x] Use the `useOnClickOutside` hook from neeto-commons-frontend to close the popover when the user clicks outside.

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please review the new changes to UI.

**Review by AbhayVAshokan — APPROVED** [review]
@gaagul _a https://vimeo.com/875137202/aeb4404134?share=copy

**Comment by gaagul** [comment]
> @gaagul _a https://vimeo.com/875137202/aeb4404134?share=copy

I think the mic was on mute while you were recording.

**Comment by AbhayVAshokan** [comment]
@gaagul: I have recorded it again: https://vimeo.com/875156777/1072dfa383?share=copy

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have fixed the issues and verified the changes, could you please verify it once more to find out whether I have missed any edge cases.

**Comment by AbhayVAshokan** [comment]
@gaagul _a in order to close the popover I need to click within the editor itself. I need to close it by clicking it anywhere. 

image

**Comment by gaagul** [comment]
> @gaagul _a in order to close the popover I need to click within the editor itself. I need to close it by clicking it anywhere.

@AbhayVAshokan I will merge the PR myself after fixing this outsideClick issue if everything else looks good.

**Pull request merged**
