### PR TITLE
Updated Webpack to compile emoji-mart using babel-loader

### LINKED ISSUE #252: Issues while running webpack dev server
- [x] Updating neetoEditor raises error while running `./bin/webpack-dev-server` in other projects. The reason being, the `emoji-mart` package contains JS code that is not supported by the `.browserslist` of the parent project.
- [x] Change `react-router-dom` version to `5.3.1`. As per frontend standardization, we are trying to achieve similar versions across all projects.

high-priority _t
@AbhayVAshokan _a

### PR DESCRIPTION
**Pull request by AbhayVAshokan**
Fixes #252
- Fixed issue with latest emoji-mart version not working with webpack-dev-server of neeto projects (Refer explanation below).
- Downgraded `react-router-dom` to `v5.3.1`. Frontend standardization recommends this version, and the newer version raises warnings while installing editor.

### CODE REVIEW

**Comment by AbhayVAshokan** [comment]
I have managed to solve the `emoji-mart` issue without downgrading the package. I have updated the Webpack configuration to compile the `emoji-mart` package from the `node_modules` folder again by the `babel-loader` of neetoEditor.

Here is a demo and explanation about the same: https://vimeo.com/718186685/4f4111abc5

@labeebklatif _a please review.
cc: @karthiknmenon

**Review by labeebklatif — COMMENTED** [review]
LGTM

**Comment by labeebklatif** [comment]
Similar issue in the `emoji-mart` package https://github.com/missive/emoji-mart/issues/613

**Comment by gabibianconi** [comment]
Is there a tentative date for a release with this fix? @labeebklatif

**Comment by labeebklatif** [comment]
@gabibianconi The fix is already released (v.0.3.47) on 8th Jun.

**Pull request merged**
