### PR TITLE
Added priority for emojis

### LINKED ISSUE #610: thunderstorm emoji should NOT come before thumsup emoji
https://www.loom.com/share/fb20a318663b4d868eee4a91cbdd6bca

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #610 

**Description**

- Added: priority for emojis

**Checklist**

- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**
@AbhayVAshokan _a

### CODE REVIEW

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a https://vimeo.com/799135784/f71a3eace9

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have expanded the default list with the commonly used emojis and also included the frequently used emoji list as well,
I tried to solve the issue with the pop suggestion but I was not able to fix it, I will take it up as a separate issue because the common solutions are not working.

**Review by AbhayVAshokan — APPROVED** [review]
LGTM

**Comment by AbhayVAshokan** [comment]
> I tried to solve the issue with the pop suggestion but I was not able to fix it, I will take it up as a separate issue because the common solutions are not working.

Please create a separate issue for the same.

**Pull request merged**
