### PR TITLE
Updated color scheme of icons and added divider for fixed menu

### LINKED ISSUE #835: Improve UI of `Link` extension
Ref: #833

### LINKED ISSUE #846: Update styles of fixed Menu
Ref: #833 

https://app.usebubbles.com/cXpB6DdiEMYdU7BqDLhQDH

Figma File:

https://www.figma.com/file/Osl7GBbBk0iwVMc57366nZ/neetoKB?type=design&node-id=5704-29355&mode=design&t=2PLrSqTTSXDXmnXu-4

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #846 
- Fixes #835 

**Description**

- Updated: color of menu icons
- Updated: secondary button background when option is active
- Updated: the styles of linkOption dropdown to be dynamic according to the content inside

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
- [ ] Link dropdown width: https://vimeo.com/850158179/af2496d4a0
- [ ] UI Improvements: https://vimeo.com/850159335/1c31804480

@gaagul _a

**Comment by gaagul** [comment]
Screenshot 2023-08-01 at 10 34 18 AM

If i remove the gap between buttons, it looks wierd. I think keeping the gap looks good for the editor since we are using buttons.
> * [ ]  UI Improvements: https://vimeo.com/850159335/1c31804480

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please take a look at the new UI changes.

**Comment by gaagul** [comment]
@AbhayVAshokan I have updated the styles as discussed and fixed the edgecases of LInkOption, please verify and let me know if any other changes are required for the UI.

**Review by AbhayVAshokan — APPROVED** [review]
- The width of the link dropdown is a bit too much. Match it with the Figma design.
image

@gaagul _a merge yourselves after this change.

**Pull request merged**
