### PR TITLE
Improved writing experience

### LINKED ISSUE #787: Vertical gap issue
@AbhayVAshokan @praveen-murali-ind @philson-philip 
https://www.loom.com/share/fefc631e7e7c481b9913aa1ca2e5d662

https://neerajdotname.neetokb.com/articles/europe-2023-trip
https://www.notion.so/Neeraj-Summer-2023-trip-e39e36a68aeb4005b7bf0f4e67420324

### LINKED ISSUE #788: Another take at the icons in the tool bar
@AbhayVAshokan @vysaghsekharbb @praveen-murali-ind https://www.loom.com/share/bd44c0eb0f9148d3be6d29b54fcc6596

### LINKED ISSUE #793: Room for improvement
The published version looks good. https://neeto-engineering.neetokb.com/articles/build-reusable-shared-modules

The editing version looks messy. https://neeto-engineering.neetokb.com/admin/articles/build-reusable-shared-modules/edit

https://monosnap.com/file/VphR6gke7ovUg4OBHedZRUy81rIHqH

Please refer to how notion might handle the same case and if something can be done then let's do it.

### PR DESCRIPTION
**Pull request by philson-philip**
- Fixes #793 
- Fixes #788 
- Fixes #787 

**Description**

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**
@praveen-murali-ind _a Please review

### CODE REVIEW

**Comment by AbhayVAshokan** [comment]
@sreeram-venkitesh can you please check the issue with this review app?

**Review by praveen-murali-ind — APPROVED** [review]
LGTM. @AbhayVAshokan _A Could you please review?

**Review by AbhayVAshokan — COMMENTED** [review]
@philson-philip _a 

In all these cases, the word "world" is bold. The boldness is not shown for headings since the font-weight in the default state is similar.

image


cc: @praveen-murali-ind

**Comment by philson-philip** [comment]
@AbhayVAshokan _a Please check this loom video https://www.loom.com/share/2215735063ff4e75bcb26e02a6c3fe98?sid=b73f6926-8a79-4a14-93b0-e523cea27fe1

**Review by AbhayVAshokan — APPROVED** [review]
Agreed! Let's keep this approach then.

**Pull request merged**
