### PR TITLE
Added text-color extension

### LINKED ISSUE #713: Add the color extension
- Add a color addon. Use. the neetoUI colorPicker. 

Ref: https://tiptap.dev/api/extensions/color

### LINKED ISSUE #757: Uploading status bug
Screenshot 2023-05-02 at 11 20 31 AM

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #713 
- Fixes #757 

**Description**

- Added: text-color extension

**Checklist**

- [x] I have made corresponding changes to the documentation.
- [ ] I have updated the types definition of modified exports.
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a https://vimeo.com/823242162/b0d1d08605

**Comment by gaagul** [comment]
> @gaagul _a https://vimeo.com/823242162/b0d1d08605

I will try to implement the debounce logic if it is possible , or else i will let you know and we can proceed with the same approach we have now.

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have improved the color picker with debounce logic as discussed, Please review.

**Review by AbhayVAshokan — APPROVED** [review]
@gaagul _a a small improvement. Please merge after making this change: https://vimeo.com/823680177/fdc2c94145

**Pull request merged**
