### PR TITLE
Implements missing features of the Codeblock component in NeetoWebsite custom codeblock component.

### LINKED ISSUE #1275: Implement missing features of the CodeBlock in NeetoWebsite custom CodeBlock component.
Implement the missing features so that we can replace the custom component in Neeto and Bigbinary website with the NeetoEditor CSS and JS utils and make it consistent with other products.

- [x] Update the CSS and JS utility to show line numbers in the EUI codeblock.
- [x] Show line numbers in the editor code block component.
- [x] Add copy button in the Codeblock EUI.
- [ ] Update the line number highlighting logic to support the Bigbinary blog code blocks.

Part of https://github.com/bigbinary/neeto-engineering-ui-ux/issues/350

@deepakjosp  _a
cc: @AbhayVAshokan @praveen-murali-ind

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #1275 

**Description**
- Updated codeblock line highlight to support BB blogs.
- Updated code block script to inject a copy button to the UI.
- Added line numbers to the codeblock.

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@praveen-murali-ind _a please review.

**Comment by deepakjosp** [comment]
@AbhayVAshokan _a please review. Let's merge once Praveen reviews the UI.

**Comment by deepakjosp** [comment]
@AbhayVAshokan  _a please review. Let's merge once Praveen reviews the UI.

**Review by AbhayVAshokan — COMMENTED** [review]
image

Line numbers are not rendered unless it is highlighted.

**Review by AbhayVAshokan — APPROVED** [review]
@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
Looking into this.

**Review by praveen-murali-ind — COMMENTED** [review]
@deepakjosp _a I have added the styles for the code block. Please check.

Screenshot 2024-11-28 at 5 21 17 PM

**Pull request merged**
