### PR TITLE
Image enhancements

### LINKED ISSUE #103: Better experience with images
@amaldinesh7 _a 

Please check the [loom video](https://www.loom.com/share/9eb4e8e4ef4b4f32b2fa8ea472bfccaf) attached. I feel these small enhancements will enrich the writing experience in neetoKb or wherever in the future we have the same use case. 
Please let me know your thoughts on this. 

enhancement _t discussion _t

cc: @AbhayVAshokan, @labeebklatif, @goutham-subramanyam

### PR DESCRIPTION
**Pull request by AbhayVAshokan**
Fixes #103 
Please go through this video for the live demo and a few issues that I need help on.
https://vimeo.com/675904715/c2bc6046df

To re-create my setup, fully replace `App.js` with the below code and run the `neetoDesk` application in another terminal. (`neetoDesk` provides the image upload endpoint).
```js
import React from "react";

import { Editor } from "../lib";

const App = () => {
  return (
    <div style={{ margin: "48px 60px" }}>
      <Editor
        autoFocus
        rows={27}
        heightStrategy="flexible"
        addons={["image-upload"]}
        uploadEndpoint="http://spinkart.lvh.me:9001/api/v1/desk/direct_uploads/image_upload"
      />
    </div>
  );
};

export default App;
```

@labeebklatif _a please have a look.

cc: @karthiknmenon, @amaldinesh7

### CODE REVIEW

**Comment by labeebklatif** [comment]
@goutham-subramanyam _a As discussed earlier, assigning for UI fixes for issues mentioned in video above.

cc: @karthiknmenon

**Comment by goutham-subramanyam** [comment]
@karthiknmenon _a Fixed the image highlight UI. Please check.

@AbhayVAshokan Please rebase with master. I tried rebasing but was not able to fix the conflicts in `Uploader.js`.

**Comment by karthiknmenon** [comment]
@AbhayVAshokan _a Could you please rebase and post a loom video of the changes?

**Comment by AbhayVAshokan** [comment]
@karthiknmenon _a please have a look: https://vimeo.com/696843269/16ca16bae8.

**Comment by karthiknmenon** [comment]
@labeebklatif _a The feature looks good to me. Could you please review and merge? Let's test it on kb to understand if we need to enhance it more.

**Comment by neerajsingh0101** [comment]
Looks good. 👍

**Comment by labeebklatif** [comment]
@karthiknmenon 
image
I think, since there was no better icon available, we have used a card icon for banner option (3rd option) here which looks a little out of place. Should we change this before merge or leave it as it for now?

@vysaghsekharbb Can we have an appropriate icon for this?

**Comment by labeebklatif** [comment]
Merging this as we don't want to further delay this. let's change the icon once it's available.

CC: @AbhayVAshokan @karthiknmenon

**Pull request merged**
