### PR TITLE
Added feature to convert pasted links to embeds

### LINKED ISSUE #567: Pasted loom, vimeo, and YouTube links should be converted to embeds
Embedded videos have a better user experience than clicking links. We already have support for embedding videos, but not widely used. Use `addPasteRules` method to convert supported video links to embeds on paste.

@gaagul _a

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #567 

**Description**

- Added: a feature to convert pasted video URLs to embeds.

**Checklist**

- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a

**Comment by gaagul** [comment]
@gaagul _a

**Review by AbhayVAshokan — APPROVED** [review]
Awesome 🤩 
One small thing, this feature needs to be enabled only when the `video-embed` option is active. Now, this feature is available even when no extensions are mentioned.

@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a I have made the mentioned changes and also combined the regular expressions into one , Please review.

**Review by AbhayVAshokan — APPROVED** [review]
Awesome ❤️ well written 👌

**Pull request merged**
