### PR TITLE
Removed hot-reloading from the webpack config

### LINKED ISSUE #232: Remove hot reload from webpack config
- Hot reload feature does not go well with the neetoEditor since the editor does a lot of processing in the background during mount causing it to crash the website when any code related to the editor is modified.
- Refer: https://github.com/bigbinary/neeto-editor-tiptap/pull/78

@mohit-s96 _a please take this up.

### PR DESCRIPTION
**Pull request by mohit-s96**
closes #232

### CODE REVIEW

**Comment by mohit-s96** [comment]
@AbhayVAshokan _a. Please review.

**Comment by AbhayVAshokan** [comment]
@mohit-s96 please mark all PRs `Ready for review` before assigning them for review if it is so.

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
Please perform the mentioned change. Also please refer the below video:
https://vimeo.com/712076268/14152fea58

@mohit-s96 _a

**Comment by mohit-s96** [comment]
@AbhayVAshokan _a. Please review the changes.

**Review by AbhayVAshokan — APPROVED** [review]
LGTM

**Pull request merged**
