### PR TITLE
Added logic for permitting wider range of video URL embeds

### LINKED ISSUE #122: Fix issues in video embed
- Add the previously removed video embed logic.
- Add Youtube and Vimeo validation logic to permit a wider range of URLs.

@AbhayVAshokan _a

### PR DESCRIPTION
**Pull request by AbhayVAshokan**
Fixes #122 
- Added the previously removed video embed logic in `addons`.
- Added a URL validation logic that validates and converts URLs to embed format.

Demo: https://vimeo.com/660893433/36515cf415

@amaldinesh7 _a please have a look.
cc: @karthiknmenon

### CODE REVIEW

**Comment by karthiknmenon** [comment]
@labeebklatif _a Please review.

**Comment by labeebklatif** [comment]
@AbhayVAshokan _a Please resolve the conflicts

**Comment by AbhayVAshokan** [comment]
@labeebklatif _a resolved conflicts and rebased with the latest master.

**Review by labeebklatif — APPROVED** [review]
LGTM!

**Pull request merged**
