### PR TITLE
Fixed use trans component instead of separating translated components and added translations

### LINKED ISSUE #682: Use Trans component instead of separating translated components
Ref: https://github.com/bigbinary/neeto-engineering-web/issues/355

### LINKED ISSUE #699: Add missing translations
Translations are missing in some [files](https://github.dev/bigbinary/neeto-editor/blob/main/src/components/Editor/MediaUploader/MediaEditor.jsx#L1) of this repository. Please check and add all missing translations.

### PR DESCRIPTION
**Pull request by soorajjtk**
Fixes #682 , Fixes #699

### CODE REVIEW

**Comment by soorajjtk** [comment]
@josephmathew900 _a Please review.

**Review by josephmathew900 — APPROVED** [review]
@soorajjtk _a Please replace all `kebab-case` translation keys with `camelCase` keys. 
https://github.com/bigbinary/neeto-editor/blob/b0f71cac7e5c6cf6b2b735db655e6ba186ec65c3/src/translations/en.json#L10
Please assign to @AbhayVAshokan for review after making the change.

**Comment by soorajjtk** [comment]
@AbhayVAshokan _a Please review.

**Review by AbhayVAshokan — APPROVED** [review]
LGTM

**Pull request merged**
