### PR TITLE
Removed request and response transformations

### LINKED ISSUE #635: Relax axios interceptor rules
- Currently, we have a strong assumption within neetoEditor that all the neeto-commons-frontend Axios interceptors will be present within the host application. This is not the case with the Scribble project. We need to relax a few rules.

- [ ] Keep the `transformRequestCase` and `transformResponseCase` methods false in the API calls (whichever is necessary).
- [ ] Clone the `wheel` repo and integrate neetoEditor in one route. Set up the image upload logic and verify the functionality.

If any other rules need to be relaxed we'll introduce a `isAxiosInterceptorsDisabled` prop (false by default). Adding this rule for conditionally checking the snake-case -> camel-case logic would lead to unreadable code.

@gaagul _a this is a priority _t issue. We need to pick this up this week.

### PR DESCRIPTION
**Pull request by gaagul**
Fixes #635

**Description**

- Removed: axios transformations

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
- [x] I have added the necessary label (patch/minor/major - If package publish is required).

**Reviewers**
@AbhayVAshokan _a

### CODE REVIEW

**Comment by gaagul** [comment]
Note: I have also changed the update function to ignore the transformations, since it is only used by attachments to update name it can be removed once the current error is solved.

**Comment by gaagul** [comment]
@AbhayVAshokan_a I fixed the existing issue and tested these changes on new rails app and image upload is working as expected,
Here is the [link](https://github.com/gaagul/react-rails-app.git) to the new repo for you to test the changes.
This [video](https://www.loom.com/share/4aae434fa04d44ebb2511dc417466ffa) is a demo of the changes in new application.

**Comment by gaagul** [comment]
@AbhayVAshokan _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a Conflicts have been resolved.

**Review by AbhayVAshokan — APPROVED** [review]
Nice work

**Pull request merged**
