### PR TITLE
Fixed issues with cursor navigation in codeblocks

### LINKED ISSUE #908: Cursor navigation issue with code blocks
Ref: https://vimeo.com/872810885/eba6f4cbe8

bug _t

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #908 

**Description**

- Fixed: issues with cursor navigation in codeblocks

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@gaagul _a

### CODE REVIEW

**Comment by gaagul** [comment]
@AbhayVAshokan The issue with arrow navigation in codeBlock is due to our custom implementation of codeBlock nodeView to have language selector on top of the node, This is the maximum possible solution i could come up with after trying many different approach.

**Comment by gaagul** [comment]
@AbhayVAshokan _a

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a https://abhay-ashokan.neetorecord.com/watch/0cd9ee15-b7c4-4aeb-adaa-676124c194d5

**Comment by gaagul** [comment]
Merging the PR since there was only changes to styles required.

cc: @AbhayVAshokan

**Pull request merged**
