### PR TITLE
Prevented wide images from shrinking to fit the available space

### LINKED ISSUE #687: Prevent wide images from shrinking to fit the available space
Ref: https://github.com/bigbinary/neeto-kb-web/issues/3653

@gaagul _a

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #687 

**Description**

- Changed: default figheight from 288 to auto

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Comment by gaagul** [comment]
This fixes the issues that we currently have without any change to styles.

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a https://vimeo.com/808541721/af4dea3205

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please review the change, this change to css will fix the extra height issue in editor content, adding a similar change to the neetoKb preview page styles will fix the issue there also.

**Comment by AbhayVAshokan** [comment]
@gaagul _a https://vimeo.com/808563322/96cd1b905f

**Comment by gaagul** [comment]
@AbhayVAshokan _a Please review.

**Review by AbhayVAshokan — APPROVED** [review]
Looks alright to me.

**Pull request merged**
