### PR TITLE
Support for custom slash commands

### LINKED ISSUE #38: Support for custom Slash Command option
Add support for including custom Slash Command action along with the predefined ones.

### PR DESCRIPTION
**Pull request by labeebklatif**
Fixes #38 

@amaldinesh7 _a Please review the code

cc: @karthiknmenon

### CODE REVIEW

**Comment by labeebklatif** [comment]
@amaldinesh7 @karthiknmenon Please have a look at the [demo](https://www.loom.com/share/cd674535854840588e1fb828fd2df89e?from_recorder=1&focus_title=1).

**Comment by sandip-mane** [comment]
This feature is needed in neetoDesk. Could we merge the PR if it's ready?

**Comment by labeebklatif** [comment]
> This feature is needed in neetoDesk. Could we merge the PR if it's ready?

Asked to improvise this feature by including the sub items inside slash command items. This is WIP

**Comment by amaldinesh7** [comment]
Merging this PR for now, keyboard navigation issues can be taken as an enhancement @labeebklatif @AbhayVAshokan @karthiknmenon .

**Pull request merged**
