### PR TITLE
Creates a playground for neetoEditor in the storybook using the live examples plugin.

### LINKED ISSUE #1158: Create a playground for neetoEditor in the storybook using the live examples plugin.
Create a playground for neetoEditor in the storybook using the [live examples plugin](https://storybook.js.org/addons/storybook-addon-live-examples).

Part of https://github.com/bigbinary/neeto-editor/issues/1100

@deepakjosp  _a

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #1158

**Description**
image

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [ ] ~I have verified the functionality in some of the neeto web-apps.~
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@AbhayVAshokan  _a please review.

**Comment by deepakjosp** [comment]
@deepakjosp  _a

**Comment by deepakjosp** [comment]
@AbhayVAshokan  _a please review.

**Review by AbhayVAshokan — APPROVED** [review]
Great work 🎉 

@deepakjosp _a please replace "Variable A" with "email" and take a look at why the rendered content is "null". Everything else looks fine. You may merge it yourself and post a message in #neeto-hq about this feature.

image

**Pull request merged**
