### PR TITLE
Changed the occurrences of neeto-editor-tiptap to neeto-editor

### LINKED ISSUE #315: Rename repository to neeto-editor
@AbhayVAshokan _a

### PR DESCRIPTION
**Pull request by AbhayVAshokan**
Fixes #315

**Description**

- Changed: **BREAKING** the CDN for editor content styles from https://cdn.jsdelivr.net/gh/bigbinary/neeto-editor-tiptap@master/dist/editor-content.min.css to https://cdn.jsdelivr.net/gh/bigbinary/neeto-editor@master/dist/editor-content.min.css.

**Checklist**

- [x] I have performed a self-review of my code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).
- [x] I have followed the suggested description format and styling.

**Reviewers**

- This PR is part of renaming the repository to `neeto-editor`.
- The renaming of the repository itself will be done next week to prevent CDN from returning a 404 code for existing repos.

https://vimeo.com/740351915/cc7bb0b452

@karthiknmenon _a please review.

### CODE REVIEW

**Review by karthiknmenon — APPROVED** [review]
LGTM.

@labeebklatif @amaldinesh7 Please review.

**Review by labeebklatif — APPROVED** [review]
LGTM. @amaldinesh7 _a can you confirm and merge

**Review by amaldinesh7 — CHANGES_REQUESTED** [review]
@AbhayVAshokan _a Please make the changes as discussed over call.

**Comment by AbhayVAshokan** [comment]
@amaldinesh7 _a please check.

**Review by amaldinesh7 — APPROVED** [review]

**Pull request merged**
