### PR TITLE
Updated the storybook documentation

### LINKED ISSUE #987: Add docs regarding difference between image_wrapper and video_wrapper
https://yedhin.neetorecord.com/watch/b4302e69-224a-447b-b482-83406a1d8e81

@gaagul _a

cc: @AbhayVAshokan

### LINKED ISSUE #1003: Typo in docs
`isEditorEmpty`

image

### LINKED ISSUE #1004: Add documentation for newly exported functions
Add documentation for the following functions:
- [x] removeEmptyTags
- [x] isEditorContentWithinLimit
- [x] substituteVariables,
- [x] isEditorOveryalsActive
- [x] isEmojiSuggestionsMenuActive
- [x] transformEditorContent

documentation _t

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #1003 
- Fixes #1004 
- Fixes #987 

**Description**

- Updated: Storybook documentation

**Checklist**

- [x] I have made corresponding changes to the documentation.
~~- [ ] I have updated the types definition of modified exports.~~
~~- [ ] I have verified the functionality in some of the neeto web-apps.~~
~~- [ ] I have added the necessary label (patch/minor/major - If package publish
      is required).~~

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Review by AbhayVAshokan — APPROVED** [review]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a Could you please verify if the latest changes to documentation are good enough?

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
Merging the PR.

**Pull request merged**
