### PR TITLE
Added fullscreen preview for images inside editor

### LINKED ISSUE #1083: Ability to see a larger image
After uploading the image in the editor, the images are shown in the editor.

- [ ] There should be a way to maximize the images to show in full-screen modal to see a larger preview

client _t

//cc @AbhayVAshokan @neerajsingh0101

### PR DESCRIPTION
**Pull request by gaagul**
- Fixes #1083 

**Description**

- Added: Fullscreen preview for images inside editor

**Checklist**

~~- [ ] I have made corresponding changes to the documentation.~~
~~- [ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

**Reviewers**

@AbhayVAshokan _a

### CODE REVIEW

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@gaagul _a

https://abhay-ashokan.neetorecord.com/watch/a9a6a30d-4bf2-4b63-92f5-a57f34a9c1ce

Image: https://github.com/bigbinary/neeto-editor/assets/35297280/b3a5a68a-1628-47df-9e1a-a5ec95997a6a

**Comment by gaagul** [comment]
> Image: https://github.com/bigbinary/neeto-editor/assets/35297280/b3a5a68a-1628-47df-9e1a-a5ec95997a6a

I will take a look at the styles issue using this image.

**Comment by gaagul** [comment]
@AbhayVAshokan Please let me know if these changes looks good: https://gaagul-gigi.neetorecord.com/watch/54d5696e-2352-4af5-bb7b-d7d2e4dd01fd, We can merge once confirmed.

**Comment by AbhayVAshokan** [comment]
@gaagul the changes look great!

**Review by AbhayVAshokan — APPROVED** [review]

**Pull request merged**
