### PR TITLE
Added feature to resize images

### LINKED ISSUE #280: Add ability to resize uploaded images
Part of #277 
- There is no control over the size of the uploaded images.
- Add a visible border which could be dragged to resize.

@AbhayVAshokan _a

### PR DESCRIPTION
**Pull request by AbhayVAshokan**
Fixes #280

**Description**

- Added the ability to resize images.
- Removed banner mode for images.

**Checklist**

- [x] I have performed a self-review of my code.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).
- [x] I have followed the suggested description format and styling.

**Reviewers**

@labeebklatif _a
Demo: https://vimeo.com/731647968/db0b887aa6

### CODE REVIEW

**Comment by labeebklatif** [comment]
@karthiknmenon _a Please confirm if this looks good to you and if the banner mode can be removed.

**Comment by karthiknmenon** [comment]
@labeebklatif _a looks good to me.

**Comment by AbhayVAshokan** [comment]
@labeebklatif _a please have a look.
https://vimeo.com/733141807/9a693301e2

**Review by labeebklatif — APPROVED** [review]
LGTM

**Pull request merged**
