### PR TITLE
Audit and improves the link component.

### LINKED ISSUE #1108: Audit and improve the Link component.
Part of https://github.com/bigbinary/neeto-editor/issues/1100

- [x] Fix inconsistencies in the colors used on popover menu.
- [x] Fix the unsmooth rendering of the link component.
- [x] Fix the text selection becoming invisible when the editor loses focus.
- [x] Fix the bugs in the positioning of the arrow and the popover menu.
- [x] Fix the bug in the position of the popover when a second link is clicked while popover of the first one was already visible.

@deepakjosp  _a

### PR DESCRIPTION
**Pull request by deepakjosp**
- Fixes #1108

**Description**
Fixes the issues with the link and it's popover component.

Screenshots
Before
image

After
image

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
- [ ] ~I have added the necessary label (patch/minor/major - If package publish
      is required).~

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@praveen-murali-ind  _a please review.

**Comment by praveen-murali-ind** [comment]
@sreeram-venkitesh _a Could you please check the deployment?

**Comment by sreeram-venkitesh** [comment]
Health check was failing, I've fixed it and redeployed both the NeetoEditor PRs.

**Comment by deepakjosp** [comment]
@AbhayVAshokan _a please review.

**Review by AbhayVAshokan — APPROVED** [review]
Looking good. Can you please make sure that these elements are of the same font size? You can merge the PR once done.

@deepakjosp _a: 
image

**Pull request merged**
