### PR TITLE
Implements responsive menu using the three dot approach.

### LINKED ISSUE #1112: Implement responsive Menu using three dot menu approach
@deepakjosp _a As discussed, please start working on this once https://github.com/bigbinary/neeto-editor/pull/1111 is merged.

cc @AbhayVAshokan 

Ref - https://github.com/bigbinary/neeto-editor/issues/1100#issuecomment-2133641974

GitHub Ref

https://github.com/bigbinary/neeto-editor/assets/48869249/c8fe076f-777f-4f22-b9ec-fe292c00bbdd

### PR DESCRIPTION
**Pull request by deepakjosp**
Fixes #1112 

**Description**

**Checklist**

- [ ] ~I have made corresponding changes to the documentation.~
- [ ] ~I have updated the types definition of modified exports.~
- [x] I have verified the functionality in some of the neeto web-apps.
- [ ] ~I have added the necessary label (patch/minor/major - If package publish
      is required).~

**Reviewers**

### CODE REVIEW

**Comment by deepakjosp** [comment]
@praveen-murali-ind  _a please review.

**Review by praveen-murali-ind — APPROVED** [review]
LGTM. @AbhayVAshokan _A Please review.

**Review by AbhayVAshokan — COMMENTED** [review]
This is looking really cool 👌 

@deepakjosp _a: https://abhay-ashokan.neetorecord.com/watch/48fcc6fd-4efd-4505-9c8d-b9dbd5815e32

**Comment by deepakjosp** [comment]
@AbhayVAshokan  _a The warnings seen in the planner console are not from the dropdown we use in the fixed menu. The rest of the [mentioned issues](https://github.com/bigbinary/neeto-editor/pull/1118#pullrequestreview-2092711772) are fixed. Please review.

image
image

**Pull request merged**
